reviews:
  path_filters:
    - "!__screenshots__/**"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "[skip ci]"
      - "update screenshots"
    drafts: false
  ignore_keyword_in_comment:
    - "[skip ci]"
